version: "3.9"

services:

  postgres:
    image: postgres:17

    container_name: flowforge-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: flowforge
      POSTGRES_PASSWORD: flowforge
      POSTGRES_DB: flowforge

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: